@echo off
echo Renaming folders...
ren erp-admin erp
ren erp-store ecommerce
ren erp-automation automation
ren erp-api api
echo Adding changes to git...
git add .
echo Committing changes...
git commit -m "refactor: simplify directory names for orchestration"
echo Pushing to GitHub...
git push
echo Done!
